### PR TITLE
Make Banner component generic

### PR DESCRIPTION
**Pull request by Readpato**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Make banner generic to allow displaying of diverse content in the app.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

Enables https://github.com/Schroedinger-Hat/schroedinger-hat/issues/214
Enables https://github.com/Schroedinger-Hat/schroedinger-hat/issues/186

### CODE REVIEW

**Comment by TheJoin95** [comment]
Could you attach an image of the banner please?

**Comment by Readpato** [comment]
@TheJoin95 Sure! I have made an additional commit to increase the font-size of the contained text.

image

**Comment by TheJoin95** [comment]
Top! Could you also check that on the mobile ? I'll approve it then

**Comment by Readpato** [comment]
Sure, here we go in iPhone 14 Pro Max and iPhone XR

image
image

**Review by TheJoin95 — APPROVED** [review]
Lovely, nice work so far

**Pull request merged**
